# Get editor completions based on the config schema
'$schema' = 'https://starship.rs/config-schema.json'

[battery]
full_symbol = ' '
charging_symbol = ' '
discharging_symbol = ' '
unknown_symbol = ' '
empty_symbol = ' '

[[battery.display]]
threshold = 100

[cmd_duration]
# show_milliseconds = true
show_notifications = true
